baseURL = "https://dkremez.github.io/"
languageCode = "en"
title = "Dzmitry Kremez"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-153716840-1"

# Page settings
[params]
    author = "Dzmitry Kremez"
    description = "DevResume - Personal online CV. Created with Hugo - Golang site generator"
    primaryColor = "#ec1a24"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Dzmitry Kremez"
        tagline = "Senior Software Engineer"
        avatar = "avatar.jpg"

    [params.contact]
        enable = true
        location = "Minsk"
        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+375295103865"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "mr.dkremez@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "https://github.com/dkremez"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/React"
        [[params.skills.list.items]]
        details = "Ruby"
        [[params.skills.list.items]]
        details = "Node.js"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "AWS/Digital Ocean/Heroku/GCP"
        [[params.skills.list.items]]
        details = "CI/CD"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"
        [[params.skills.list.items]]
        details = "Ownership"
        [[params.skills.list.items]]
        details = "Team leading experience"





    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computer Science (Unfinished)"
        university = "Belarusian State University of Informatics and Radioelectronics"
        dates = "2014 - 2015"
        [[params.education.list]]
        degree = "BSc in Computer Science"
        university = "Belarusian State Academy of Telecommunications"
        dates = "2007 - 2014"



    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "iTechArt Hackaton 1st place"
        body = "iTechArt Hackaton"
        date = "2015"




    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional (Upper-Intermediate)"
        [[params.languages.list]]
        name = "Russian"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Driving"
        [[params.interests.list]]
        name = "Reading"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Exercises"








    [params.summary]
        enable = true
        text = "As a Software Engineer with 7+ years of experience on Web and related fields, I specialize in front-end, backend development and software architecture. It means that I have a familiarity with each layer of development and a commitment to gaining expertise in all software technology. I enjoy working with small businesses and individual decision makers to provide architectural and custom business solutions that help my clients resolve mission-critical problems, grow their business, and improve their revenue stream and profitability."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Group Manager"
        dates = "2017 - Present"
        company = "iTechArt Group"
        details = "As a Group Manager, my responsibilities are:"
        [[params.experience.list.items]]
        details = "Management of software development group."
        [[params.experience.list.items]]
        details = "Financial indicators, KPI management."
        [[params.experience.list.items]]
        details = "Participate in pre-sales activities."
        [[params.experience.list.items]]
        details = "Communication with company customers."
        [[params.experience.list.items]]
        details = "Personnel management: staffing, training, performance review conducting, delegating."
        [[params.experience.list.items]]
        details = "Improvement of software development processes."
        [[params.experience.list.items]]
        details = "Organize local technology meetups and knowledge sharing sessions."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "iTechArt Group"
        details = "As Lead Full Stack Developer my duties list included:"
        [[params.experience.list.items]]
        details = "Leading a software development team."
        [[params.experience.list.items]]
        details = "Hold communications between development teams, product managers, and other stakeholders."
        [[params.experience.list.items]]
        details = "Make decisions within their team about how to optimize work for features to be implemented, when possible in order of the priority."
        [[params.experience.list.items]]
        details = "Analysis of code structure, architecture."
        [[params.experience.list.items]]
        details = "Back-end & Front-end development."

        [[params.experience.list]]
        title = "Software Egnineer"
        dates = "2013 - 2016"
        company = "iTechArt Group"
        details = "I worked on many company projects as regular Software Developer. My responsibilities were to:"
        [[params.experience.list.items]]
        details = "Analysis of code structure, architecture."
        [[params.experience.list.items]]
        details = "Back-end & Front-end development."
        [[params.experience.list.items]]
        details = "DB designing, performance optimizations."
        [[params.experience.list.items]]
        details = "Code refactoring. Improvement of tests coverage."
        [[params.experience.list.items]]
        details = "Infrastructure configuration and deployment."
        [[params.experience.list.items]]
        details = "Daily meetings with customers."

        [[params.experience.list]]
        title = "Ruby on Rails and Java SE coach"
        dates = "2013 - 2014"
        company = "BigSoft"
        details = "I taught students basic knowledge about programming skills, OOP practices, frameworks API. I give them homework tasks and advice for code design standards. As a result, they built a test project.."
      









    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Insurance company (NDA)"
        meta = "Lead Software Egnineer"
        tagline = "Application is an online insurance company for consumers and enterprises. It provides a better experience for other business owners and a concierge service of business insurance management."
        
        [[params.projects.list]]
        title = "Harvest"
        meta = "Senior Software Developer"
        tagline = "Harvest is the digital content platform for the investor community where investment organizations distribute their latest insights, empowering investors to make the most informed decisions."
        
        [[params.projects.list]]
        title = "Caredox"
        meta = "Software Developer"
        tagline = "CareDox is a care coordination platform for parents and schools. It automate and streamline information collection and access to improve child safety."

        [[params.projects.list]]
        title = "Beauty Booked"
        meta = "Software Developer"
        tagline = "Beauty Booked is an online platform that enables users to search, discover, and book appointments with salons and spas."

        [[params.projects.list]]
        title = "Scidea"
        meta = "Software Developer"
        tagline = "Scidea is a web-based, consumer-facing Learning Management System that enables employees, members, partners or any learners across an organization and in different countries to access training and events from a single online platform."

        [[params.projects.list]]
        title = "GruupMeet"
        meta = "Software Developer"
        tagline = "The application includes a tracking function and user interaction features to help manage group airport arrivals. Application focuses on personal communication with meeting attendees and a tracking feature to pro-actively stay attended to arrivals/attendees."










    [params.information]
        enable = true
        [[params.information.list]]
        title="Additional Education"
        [[params.information.list.items]]
        details = "2019 · ManageIT.by - Hard Skills for IT-Managers"
        [[params.information.list.items]]
        details = "2018 · Tensor.by - Machine Learning"
        [[params.information.list.items]]
        details = "2018 · Belhard - Introduction into Machine Learning"
        [[params.information.list.items]]
        details = "2017 · Gronis - Algorithms and Data Structures"
        [[params.information.list.items]]
        details = "2013 · Itransition - Production Software Development"
        [[params.information.list.items]]
        details = "2012 · BigSoft - Java SE, Java EE"

        [[params.information.list]]
        title = "Interests"
        details = "Travelling, Driving, Reading, Snowboarding, Exercises"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/dkremez"
        title = "dkremez"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/dzmitry-kremez-290a8181"
        title = "dzmitry-kremez"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/dima_kremez"
        title = "@dima_kremez"





